version: '2.1'

services:
  nextjs:
    image: nextjs
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 8010:8010
      - 9229:9229
    ## set your startup file here
    command: node --inspect=0.0.0.0:9229 index.js